import Head from "next/head";
import Image from "next/image";
import { Card, Grid, Text } from "@nextui-org/react";
import Header from "@/components/navbar";
import HomePage from "./home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rideshare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePage />
    </>
  );
}
